trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: node-aks-app
  acrName: nimmyacr
  acrLoginServer: nimmyacr.azurecr.io

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'

- script: |
    npm install
  displayName: 'Install Dependencies'

- script: |
    docker build -t $(acrLoginServer)/$(imageName):$(Build.BuildId) .
  displayName: 'Docker Build'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-aks-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az acr login --name $(acrName)

- script: |
    docker push $(acrLoginServer)/$(imageName):$(Build.BuildId)
  displayName: 'Push to ACR'