trigger:
- main

variables:
  imageName: node-app
  acrName: nimmyacr.azurecr.io
  dockerTag: $(Build.BuildId)
  k8sManifest: k8s/deployment.yaml

stages:

# =========================
# BUILD & PUSH IMAGE
# =========================
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest

    steps:

    - task: UseNode@1
      inputs:
        version: '18.x'

    - script: |
        npm install
      displayName: Install Dependencies

    - script: |
        docker build -t $(acrName)/$(imageName):$(dockerTag) .
      displayName: Build Docker Image

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azure-aks-connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name nimmyacr

    - script: |
        docker push $(acrName)/$(imageName):$(dockerTag)
      displayName: Push Image


# =========================
# UPDATE MANIFEST USING sed
# =========================
- stage: UpdateManifest
  dependsOn: Build

  jobs:
  - job: Update
    pool:
      vmImage: ubuntu-latest

    steps:

    - checkout: self
      persistCredentials: true

    - script: |
        echo "Updating deployment.yaml"

        sed -i "s|image:.*|image: nimmyacr.azurecr.io/node-app:$(Build.BuildId)|g" k8s/deployment.yaml

        echo "Updated YAML:"
        cat k8s/deployment.yaml
      displayName: Update image tag using sed

    - script: |
        git config user.email "pipeline@azure.com"
        git config user.name "azure-pipeline"

        git add k8s/deployment.yaml

        git commit -m "Update image tag to $(Build.BuildId)" || echo "No changes"

        git push origin HEAD:main
      displayName: Commit updated manifest


# =========================
# DEPLOY TO AKS
# =========================
- stage: Deploy
  dependsOn: UpdateManifest

  jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-latest

    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azure-aks-connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |

          az aks get-credentials \
            --resource-group YOUR-RG \
            --name YOUR-AKS-CLUSTER

          kubectl apply -f k8s/deployment.yaml